version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-notes
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16.4-alpine
    container_name: postgres
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
