version: '3.9'

networks:
  smart-notes-app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-notes
    networks:
      - smart-notes-app-network
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${PORT}:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  db:
    image: postgres:16.4-alpine
    container_name: smart-notes-postgres
    networks:
      - smart-notes-app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
